const std = @import("std");

pub const RiskLevel = enum { low, medium, high };

pub const Classification = struct {
    category: []const u8,
    explanation: []const u8,
    risk: RiskLevel,
    recommendation: []const u8,
};

pub fn classify(path: []const u8, name: []const u8) ?Classification {
    if (equals(name, "node_modules") or equals(name, "bower_components")) {
        return .{
            .category = "Dependency folder",
            .explanation = "Installed project dependencies generated by a package manager.",
            .risk = .medium,
            .recommendation = "Usually recoverable by reinstalling dependencies; review active projects before removing.",
        };
    }

    if (equals(name, ".next") or equals(name, ".nuxt") or equals(name, ".svelte-kit") or equals(name, ".turbo")) {
        return .{
            .category = "Framework output",
            .explanation = "Cached frontend framework build output.",
            .risk = .low,
            .recommendation = "Can usually be regenerated by the framework build or dev server.",
        };
    }

    if (equals(name, "dist") or equals(name, "build") or equals(name, "out")) {
        return .{
            .category = "Build output",
            .explanation = "Common generated build output directory.",
            .risk = .low,
            .recommendation = "Verify it is not the only copy of a deployable artifact before removing.",
        };
    }

    if (equals(name, "target") or equals(name, ".zig-cache") or equals(name, "zig-out") or equals(name, "__pycache__") or equals(name, ".pytest_cache")) {
        return .{
            .category = "Language build artifact",
            .explanation = "Compiler, interpreter, or test runner output generated during development.",
            .risk = .low,
            .recommendation = "Can usually be regenerated by rebuilding or rerunning tests.",
        };
    }

    if (equals(name, ".venv") or equals(name, "venv") or equals(name, "env")) {
        return .{
            .category = "Dependency folder",
            .explanation = "Python virtual environment with installed project dependencies.",
            .risk = .medium,
            .recommendation = "Confirm dependency lock files exist before removing.",
        };
    }

    if (contains(path, "/Library/Developer/Xcode/DerivedData") or contains(path, "/Library/Developer/Xcode/Archives")) {
        return .{
            .category = "Xcode artifact",
            .explanation = "Xcode build, index, or archive data.",
            .risk = .low,
            .recommendation = "Derived build data is usually regenerable; review archives before removing.",
        };
    }

    if (contains(path, "/Library/Developer/CoreSimulator")) {
        return .{
            .category = "Simulator data",
            .explanation = "iOS simulator runtime, device, or cache data.",
            .risk = .medium,
            .recommendation = "Review simulator devices and runtimes before removing.",
        };
    }

    if (contains(path, "/Library/Caches/Homebrew") or contains(path, "/.cache/Homebrew")) {
        return .{
            .category = "Homebrew cache",
            .explanation = "Downloaded Homebrew formula, cask, or bottle cache.",
            .risk = .low,
            .recommendation = "Usually safe to clean through Homebrew commands.",
        };
    }

    if (isPackageCache(path, name)) {
        return .{
            .category = "Package cache",
            .explanation = "Package manager download or build cache.",
            .risk = .medium,
            .recommendation = "Prefer the package manager cleanup command when available.",
        };
    }

    if (equals(name, "Downloads") or contains(path, "/Downloads/")) {
        return .{
            .category = "Downloads",
            .explanation = "User-downloaded files that may include installers, archives, or personal documents.",
            .risk = .high,
            .recommendation = "Review manually before removing anything.",
        };
    }

    if (equals(name, ".Trash") or contains(path, "/.Trash/") or contains(path, "/Trash/")) {
        return .{
            .category = "Trash",
            .explanation = "Items already moved to Trash.",
            .risk = .medium,
            .recommendation = "Review before emptying because deletion is permanent.",
        };
    }

    return null;
}

fn isPackageCache(path: []const u8, name: []const u8) bool {
    return equals(name, ".npm") or
        equals(name, ".pnpm-store") or
        equals(name, ".yarn") or
        contains(path, "/.bun/install/cache") or
        contains(path, "/Library/Caches/Yarn") or
        contains(path, "/Library/Caches/pnpm") or
        contains(path, "/Library/Caches/pip") or
        contains(path, "/.cache/pip") or
        contains(path, "/.cargo/registry") or
        contains(path, "/.cargo/git") or
        contains(path, "/go/pkg/mod");
}

fn equals(left: []const u8, right: []const u8) bool {
    return std.mem.eql(u8, left, right);
}

fn contains(haystack: []const u8, needle: []const u8) bool {
    return std.mem.indexOf(u8, haystack, needle) != null;
}

test "classifies representative developer artifacts" {
    try expectCategory("/tmp/app/node_modules", "node_modules", "Dependency folder", .medium);
    try expectCategory("/tmp/app/.next", ".next", "Framework output", .low);
    try expectCategory("/tmp/app/target", "target", "Language build artifact", .low);
    try expectCategory("/Users/me/Library/Developer/Xcode/DerivedData/App", "App", "Xcode artifact", .low);
    try expectCategory("/Users/me/Library/Developer/CoreSimulator/Devices", "Devices", "Simulator data", .medium);
    try expectCategory("/Users/me/.npm", ".npm", "Package cache", .medium);
    try expectCategory("/Users/me/Library/Caches/Homebrew", "Homebrew", "Homebrew cache", .low);
    try expectCategory("/Users/me/Downloads", "Downloads", "Downloads", .high);
    try expectCategory("/Users/me/.Trash", ".Trash", "Trash", .medium);
}

fn expectCategory(path: []const u8, name: []const u8, category: []const u8, risk: RiskLevel) !void {
    const actual = classify(path, name) orelse return error.ExpectedClassification;
    try std.testing.expectEqualStrings(category, actual.category);
    try std.testing.expectEqual(risk, actual.risk);
}
