const std = @import("std");

pub const RiskLevel = enum { low, medium, high };

pub const Classification = struct {
    category: []const u8,
    explanation: []const u8,
    risk: RiskLevel,
    recommendation: []const u8,
    is_protected: bool = false,
    protection_reason: ?[]const u8 = null,
};

pub fn classify(path: []const u8, name: []const u8) ?Classification {
    if (equals(name, ".git") or contains(path, "/.git/")) {
        return .{
            .category = "Source control",
            .explanation = "Git repository metadata, object history, refs, and local repository state.",
            .risk = .high,
            .recommendation = "Do not delete directly. Delete the whole project only if you no longer need it.",
            .is_protected = true,
            .protection_reason = "Source control metadata",
        };
    }

    if (contains(path, "/Library/Containers/com.docker.docker") or contains(path, "/.docker/") or contains(path, "/Docker.raw")) {
        return .{
            .category = "Developer artifacts",
            .explanation = "Docker-visible storage such as local images, containers, volumes, or Docker Desktop data.",
            .risk = .medium,
            .recommendation = "Use Docker Desktop or docker cleanup commands so active containers and volumes are handled correctly.",
        };
    }

    if (equals(name, "Applications") or endsWith(path, ".app") or contains(path, "/Applications/")) {
        return .{
            .category = "Applications and app support",
            .explanation = "Installed applications or application bundles.",
            .risk = .high,
            .recommendation = "Uninstall through the app, vendor uninstaller, or system settings when available.",
        };
    }

    if (contains(path, "/Library/Application Support") or contains(path, "/Library/Containers") or contains(path, "/Library/Group Containers")) {
        return .{
            .category = "Applications and app support",
            .explanation = "Application support data, settings, containers, or local app state.",
            .risk = .high,
            .recommendation = "Review the owning application before removing because this may include user data.",
        };
    }

    if (equals(name, "Documents") or contains(path, "/Documents/") or contains(path, "/Desktop/")) {
        return .{
            .category = "Documents",
            .explanation = "User-created documents or desktop files.",
            .risk = .high,
            .recommendation = "Review manually and back up important files before deleting.",
        };
    }

    if (equals(name, "Pictures") or equals(name, "Movies") or equals(name, "Music") or contains(path, "/Pictures/") or contains(path, "/Movies/") or contains(path, "/Music/") or hasMediaExtension(name)) {
        return .{
            .category = "Media",
            .explanation = "Photo, video, music, or other media content.",
            .risk = .high,
            .recommendation = "Review manually because media often contains personal or source files.",
        };
    }

    if (isProtectedPath(path)) {
        return .{
            .category = "System-adjacent space",
            .explanation = "Protected operating system or system-managed storage.",
            .risk = .high,
            .recommendation = "Do not offer this path for normal cleanup; review only with explicit expert intent.",
            .is_protected = true,
            .protection_reason = "Protected system location",
        };
    }

    if (contains(path, "/Library/Logs") or contains(path, "/private/var/log") or contains(path, "/private/var/folders")) {
        return .{
            .category = "System-adjacent space",
            .explanation = "System-managed logs, temporary data, or operating system adjacent files.",
            .risk = .high,
            .recommendation = "Avoid manual deletion unless you know the owning system service and impact.",
        };
    }

    if (equals(name, "node_modules") or equals(name, "bower_components")) {
        return .{
            .category = "Developer artifacts",
            .explanation = "Installed project dependencies generated by a package manager.",
            .risk = .medium,
            .recommendation = "Usually recoverable by reinstalling dependencies; review active projects before removing.",
        };
    }

    if (equals(name, ".next") or equals(name, ".nuxt") or equals(name, ".svelte-kit") or equals(name, ".turbo")) {
        return .{
            .category = "Developer artifacts",
            .explanation = "Cached frontend framework build output.",
            .risk = .low,
            .recommendation = "Can usually be regenerated by the framework build or dev server.",
        };
    }

    if (equals(name, "dist") or equals(name, "build") or equals(name, "out")) {
        return .{
            .category = "Developer artifacts",
            .explanation = "Common generated build output directory.",
            .risk = .low,
            .recommendation = "Verify it is not the only copy of a deployable artifact before removing.",
        };
    }

    if (equals(name, "target") or equals(name, ".zig-cache") or equals(name, "zig-out") or equals(name, "__pycache__") or equals(name, ".pytest_cache")) {
        return .{
            .category = "Developer artifacts",
            .explanation = "Compiler, interpreter, or test runner output generated during development.",
            .risk = .low,
            .recommendation = "Can usually be regenerated by rebuilding or rerunning tests.",
        };
    }

    if (equals(name, ".venv") or equals(name, "venv") or equals(name, "env")) {
        return .{
            .category = "Developer artifacts",
            .explanation = "Python virtual environment with installed project dependencies.",
            .risk = .medium,
            .recommendation = "Confirm dependency lock files exist before removing.",
        };
    }

    if (contains(path, "/Library/Developer/Xcode/DerivedData") or contains(path, "/Library/Developer/Xcode/Archives")) {
        return .{
            .category = "Developer artifacts",
            .explanation = "Xcode build, index, or archive data.",
            .risk = .low,
            .recommendation = "Derived build data is usually regenerable; review archives before removing.",
        };
    }

    if (contains(path, "/Library/Developer/CoreSimulator")) {
        return .{
            .category = "Developer artifacts",
            .explanation = "iOS simulator runtime, device, or cache data.",
            .risk = .medium,
            .recommendation = "Review simulator devices and runtimes before removing.",
        };
    }

    if (contains(path, "/Library/Caches/Homebrew") or contains(path, "/.cache/Homebrew")) {
        return .{
            .category = "Developer artifacts",
            .explanation = "Downloaded Homebrew formula, cask, or bottle cache.",
            .risk = .low,
            .recommendation = "Usually safe to clean through Homebrew commands.",
        };
    }

    if (isPackageCache(path, name)) {
        return .{
            .category = "Developer artifacts",
            .explanation = "Package manager download or build cache.",
            .risk = .medium,
            .recommendation = "Prefer the package manager cleanup command when available.",
        };
    }

    if (equals(name, "Caches") or contains(path, "/Library/Caches/") or contains(path, "/.cache/")) {
        return .{
            .category = "Caches",
            .explanation = "Regenerable cache data created by apps or tools.",
            .risk = .medium,
            .recommendation = "Prefer app-specific or tool-specific cleanup commands when available.",
        };
    }

    if (equals(name, "Downloads") or contains(path, "/Downloads/")) {
        return .{
            .category = "Downloads",
            .explanation = "User-downloaded files that may include installers, archives, or personal documents.",
            .risk = .high,
            .recommendation = "Review manually before removing anything.",
        };
    }

    if (equals(name, ".Trash") or contains(path, "/.Trash/") or contains(path, "/Trash/")) {
        return .{
            .category = "Trash",
            .explanation = "Items already moved to Trash.",
            .risk = .medium,
            .recommendation = "Review before emptying because deletion is permanent.",
        };
    }

    return .{
        .category = "Unknown",
        .explanation = "No specific storage category matched this item.",
        .risk = .high,
        .recommendation = "Review manually before deleting.",
    };
}

fn isPackageCache(path: []const u8, name: []const u8) bool {
    return equals(name, ".npm") or
        equals(name, ".pnpm-store") or
        equals(name, ".yarn") or
        contains(path, "/.bun/install/cache") or
        contains(path, "/Library/Caches/Yarn") or
        contains(path, "/Library/Caches/pnpm") or
        contains(path, "/Library/Caches/pip") or
        contains(path, "/.cache/pip") or
        contains(path, "/.cargo/registry") or
        contains(path, "/.cargo/git") or
        contains(path, "/go/pkg/mod");
}

fn equals(left: []const u8, right: []const u8) bool {
    return std.mem.eql(u8, left, right);
}

fn startsWith(haystack: []const u8, needle: []const u8) bool {
    return std.mem.startsWith(u8, haystack, needle);
}

fn endsWith(haystack: []const u8, needle: []const u8) bool {
    return std.mem.endsWith(u8, haystack, needle);
}

fn contains(haystack: []const u8, needle: []const u8) bool {
    return std.mem.indexOf(u8, haystack, needle) != null;
}

fn isProtectedPath(path: []const u8) bool {
    return startsWith(path, "/System/") or
        startsWith(path, "/usr/") or
        startsWith(path, "/bin/") or
        startsWith(path, "/sbin/") or
        startsWith(path, "/private/etc/") or
        startsWith(path, "/private/var/db/") or
        startsWith(path, "/Library/Apple/") or
        startsWith(path, "/Library/Preferences/SystemConfiguration/");
}

fn hasMediaExtension(name: []const u8) bool {
    return endsWith(name, ".jpg") or
        endsWith(name, ".jpeg") or
        endsWith(name, ".png") or
        endsWith(name, ".heic") or
        endsWith(name, ".mov") or
        endsWith(name, ".mp4") or
        endsWith(name, ".mp3") or
        endsWith(name, ".wav");
}

test "classifies representative general storage categories" {
    try expectCategory("/Applications/Preview.app", "Preview.app", "Applications and app support", .high);
    try expectCategory("/Users/me/Library/Application Support/Foo", "Foo", "Applications and app support", .high);
    try expectCategory("/Users/me/Documents/Report.pdf", "Report.pdf", "Documents", .high);
    try expectCategory("/Users/me/Pictures/photo.jpg", "photo.jpg", "Media", .high);
    try expectCategory("/Users/me/Library/Caches/com.example", "com.example", "Caches", .medium);
    try expectCategory("/private/var/log/system.log", "system.log", "System-adjacent space", .high);
    try expectProtected("/System/Library/CoreServices", "CoreServices");
    try expectCategory("/Users/me/Downloads", "Downloads", "Downloads", .high);
    try expectCategory("/Users/me/.Trash", ".Trash", "Trash", .medium);
    try expectCategory("/Users/me/mystery.bin", "mystery.bin", "Unknown", .high);
}

test "classifies representative developer artifacts" {
    try expectCategory("/tmp/app/node_modules", "node_modules", "Developer artifacts", .medium);
    try expectCategory("/tmp/app/.next", ".next", "Developer artifacts", .low);
    try expectCategory("/tmp/app/target", "target", "Developer artifacts", .low);
    try expectCategory("/Users/me/Library/Developer/Xcode/DerivedData/App", "App", "Developer artifacts", .low);
    try expectCategory("/Users/me/Library/Developer/CoreSimulator/Devices", "Devices", "Developer artifacts", .medium);
    try expectCategory("/Users/me/.npm", ".npm", "Developer artifacts", .medium);
    try expectCategory("/Users/me/Library/Caches/Homebrew", "Homebrew", "Developer artifacts", .low);
    try expectCategory("/Users/me/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw", "Docker.raw", "Developer artifacts", .medium);
}

test "protects source control metadata from routine cleanup" {
    const actual = classify("/tmp/app/.git", ".git") orelse return error.ExpectedClassification;
    try std.testing.expectEqualStrings("Source control", actual.category);
    try std.testing.expectEqual(RiskLevel.high, actual.risk);
    try std.testing.expect(actual.is_protected);
    try std.testing.expectEqualStrings("Source control metadata", actual.protection_reason orelse "");
    try std.testing.expect(std.mem.indexOf(u8, actual.recommendation, "Do not delete directly") != null);
}

fn expectCategory(path: []const u8, name: []const u8, category: []const u8, risk: RiskLevel) !void {
    const actual = classify(path, name) orelse return error.ExpectedClassification;
    try std.testing.expectEqualStrings(category, actual.category);
    try std.testing.expectEqual(risk, actual.risk);
}

fn expectProtected(path: []const u8, name: []const u8) !void {
    const actual = classify(path, name) orelse return error.ExpectedClassification;
    try std.testing.expect(actual.is_protected);
    try std.testing.expectEqualStrings("Protected system location", actual.protection_reason orelse "");
}
