import { describe, expect, test } from "bun:test";

import { scanResultSchema } from "./schema";

describe("scan result schema", () => {
  test("accepts the scanner JSON contract", () => {
    const result = scanResultSchema.parse({
      schemaVersion: 1,
      root: {
        path: "/tmp/zpace",
        name: "zpace",
        type: "directory",
        logicalSize: 12,
        allocatedSize: null,
        childCount: 1,
        status: "complete",
        children: [
          {
            path: "/tmp/zpace/file.txt",
            name: "file.txt",
            type: "file",
            logicalSize: 12,
            allocatedSize: 4096,
            childCount: 0,
            status: "complete",
            classification: {
              category: "Developer artifacts",
              explanation: "Installed project dependencies generated by a package manager.",
              risk: "medium",
              recommendation: "Usually recoverable by reinstalling dependencies; review active projects before removing.",
              isProtected: false,
              protectionReason: null,
            },
            children: [],
          },
        ],
      },
      summary: {
        totalLogicalSize: 12,
        totalAllocatedSize: 4096,
        likelyReclaimableSize: 0,
        fileCount: 1,
        folderCount: 1,
        warningCount: 1,
        inaccessibleCount: 1,
        skippedCount: 0,
        protectedCount: 0,
        freeSize: null,
        purgeableSize: null,
        durationMs: 3,
        largestItems: [
          {
            path: "/tmp/zpace/file.txt",
            name: "file.txt",
            type: "file",
            logicalSize: 12,
            classification: {
              category: "Developer artifacts",
              explanation: "Installed project dependencies generated by a package manager.",
              risk: "medium",
              recommendation: "Usually recoverable by reinstalling dependencies; review active projects before removing.",
              isProtected: false,
              protectionReason: null,
            },
          },
        ],
        categories: [
          {
            category: "Developer artifacts",
            logicalSize: 12,
            itemCount: 1,
            likelyReclaimableSize: 0,
          },
        ],
      },
      diagnostics: [
        {
          path: "/tmp/zpace/private",
          kind: "inaccessible",
          severity: "warning",
          message: "Permission denied",
          guidance: "Grant Full Disk Access to the app or terminal running zpace, then scan again.",
        },
      ],
    });

    expect(result.root.children[0]?.logicalSize).toBe(12);
    expect(result.root.children[0]?.classification?.risk).toBe("medium");
    expect(result.summary.fileCount).toBe(1);
    expect(result.summary.inaccessibleCount).toBe(1);
    expect(result.summary.freeSize).toBeNull();
    expect(result.summary.largestItems[0]?.name).toBe("file.txt");
    expect(result.summary.categories[0]?.category).toBe("Developer artifacts");
    expect(result.diagnostics[0]?.kind).toBe("inaccessible");
    expect(result.diagnostics[0]?.guidance).toContain("Full Disk Access");
  });

  test("defaults diagnostics and classification for reports during transition", () => {
    const result = scanResultSchema.parse({
      schemaVersion: 1,
      root: {
        path: "/tmp/zpace",
        name: "zpace",
        type: "directory",
        logicalSize: 0,
        allocatedSize: null,
        childCount: 0,
        status: "complete",
        children: [],
      },
      summary: {
        totalLogicalSize: 0,
        totalAllocatedSize: null,
        likelyReclaimableSize: 0,
        fileCount: 0,
        folderCount: 1,
        warningCount: 0,
        durationMs: 0,
        largestItems: [],
        categories: [],
      },
    });

    expect(result.diagnostics).toEqual([]);
    expect(result.root.classification).toBeNull();
  });
});
