import { describe, expect, test } from "bun:test";

import { scanResultSchema } from "./schema";

describe("scan result schema", () => {
  test("accepts the scanner JSON contract", () => {
    const result = scanResultSchema.parse({
      schemaVersion: 1,
      root: {
        path: "/tmp/zpace",
        name: "zpace",
        type: "directory",
        logicalSize: 12,
        allocatedSize: null,
        childCount: 1,
        status: "complete",
        children: [
          {
            path: "/tmp/zpace/file.txt",
            name: "file.txt",
            type: "file",
            logicalSize: 12,
            allocatedSize: 4096,
            childCount: 0,
            status: "complete",
            classification: {
              category: "Dependency folder",
              explanation: "Installed project dependencies generated by a package manager.",
              risk: "medium",
              recommendation: "Usually recoverable by reinstalling dependencies; review active projects before removing.",
            },
            children: [],
          },
        ],
      },
      diagnostics: [
        {
          path: "/tmp/zpace/private",
          kind: "inaccessible",
          severity: "error",
          message: "AccessDenied",
        },
      ],
    });

    expect(result.root.children[0]?.logicalSize).toBe(12);
    expect(result.root.children[0]?.classification?.risk).toBe("medium");
    expect(result.diagnostics[0]?.kind).toBe("inaccessible");
  });

  test("defaults diagnostics and classification for older scanner reports during transition", () => {
    const result = scanResultSchema.parse({
      schemaVersion: 1,
      root: {
        path: "/tmp/zpace",
        name: "zpace",
        type: "directory",
        logicalSize: 0,
        allocatedSize: null,
        childCount: 0,
        status: "complete",
        children: [],
      },
    });

    expect(result.diagnostics).toEqual([]);
    expect(result.root.classification).toBeNull();
  });
});
